config/routes.rb
Rails.application.routes.draw do

  root to: "pages#home"

  resources :bookings
  resources :sales

  post "/bookings/:id/book" => "bookings#book"
    # link_to --> "/bookings/:id/book"
    # we will need a book method in the bookings controller
    # Find the booking (params[:id])
    # Update the booking's student_id to be whoever is logged in
    # Update the booking's available property to false
    # Redirect to somewhere

  post '/comments' => 'comments#create', as: 'comments'
  delete '/comments/:id' => 'comments#destroy'

  resources :users do
    # resources :comments
  end

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  get '/logout' => 'session#destroy'

end

app/models/booking.rb
class Booking < ApplicationRecord

  belongs_to :teacher, class_name: "User", foreign_key: "teacher_id", optional: true
  belongs_to :student, class_name: "User", foreign_key: "student_id", optional: true

  # Stripe
  has_many :sales

  validates_numericality_of :price,
    greater_than: 50,
    message: "must be at least 50 cents"

end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @all_bookings = Booking.all
  end

  def show
    @booking = Booking.find_by(id: params["id"])
    @teacher_bookings = @user.teacher_bookings
    @student_bookings = @user.student_bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new( booking_params)
    @booking.teacher_id = @current_user.id
    @booking.save
    #  raise hell
    redirect_to "/users/#{@current_user.id}"
  end

  def edit
    @booking = Booking.find_by(id: params["id"])
  end

  def book
    # raise "hell"
    # Find the booking (params[:id])
    @booking = Booking.find_by(id: params["id"])
    # Update the booking's student_id to be whoever is logged in
    @booking.student_id = @current_user.id
    # Update the booking's available property to false
    @booking.available = false
    @booking.save

    BookingMailer.confirmation(@booking).deliver_now

    # CREATE YOUR PAYMENT HERE

        token = params[:stripeToken]
        # binding.pry
        charge = Stripe::Charge.create(
          amount:      @booking.price,
          currency:    "aud",
          card:        token,
          description: params[:stripeEmail]
        )

        @sale = @booking.sales.create!(
          email:      params[:stripeEmail],
          stripe_id:  charge.id
        )

        # Send email
        BookingMailer.confirmation(@booking).deliver_now
        # Show booking success
        # raise "hell"

    redirect_to "/users/#{@current_user.id}"

  end

  def update
    # Handles the submission of a form
    @booking = Booking.find_by(id: params["id"])
    @booking.update ( booking_params() )
    redirect_to booking_path(booking)
  end

  def destroy
    # Deletes a particular booking
    # raise "hell"
    @booking = Booking.find_by(id: params["id"])
    teacher_id = @booking.teacher_id
    @booking.destroy
    redirect_to "/users/#{teacher_id}"
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :start_time, :end_time, :teacher_id, :student_id, :permalink, :price)
  end

end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<div class="center row">
        <div class="col s12 m4"></div>
        <div class="box-white col s12 m4">

            <%= form_for @booking do |f| %>

            <p>
                <%= f.label :date %>
                <%= f.date_field :date, min: Date.today, required: true %>
            </p>

            <p>
                <%= f.label :start_time %>
                <%= f.time_field :start_time, required: true %>
            </p>

            <p>
                <%= f.label :end_time %>
                <%= f.time_field :end_time, required: true %>
            </p>

            <p>
                <%= f.label :price %>
                <%= f.text_field :price, min: 5, required: true  %>
            </p>

            <%= f.submit %>
            <% end %>

        </div>
    </div>
</div>

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= render partial: "form" %>

app/views/bookings/index.html.erb
<h2>My Lessons</h2>
<div class="col s12">
    <div class="card grey lighten-3">
        <div class="card-content teal-lighten-1-text">
            <% @all_bookings.each do |booking| %>
            <p>
                <%= link_to(booking.date, "/bookings/#{booking.id}") %>
                <p>Start time:
                    <%= booking.start_time %></p>
                <p>End time:
                    <%= booking.end_time %></p>
                <p>Tutor:
                    <%= booking.teacher.name%></p>
                <p>Tutor:
                    <%= booking.teacher_id%></p>
                <p>Student:
                    <%= booking.student_id%></p>
                <p>Price:
                    <%= booking.student_id%></p>
            </p>
            <%# end %>
            <% end %>
        </div>
    </div>
</div>

app/views/bookings/new.html.erb
<!-- <h2>Book a timeslot</h2> -->

<%= render( partial: "form" ) %>

app/views/bookings/show.html.erb
<h1>Your Lessons</h1>

<p>Date:
    <%= @booking.date.strftime("%B %d, %Y  %I:%M %P")  %></p>
<p>Start time:
    <%= @booking.start_time.strftime("%H: %M %P") %></p>
<p>End time:
    <%= @booking.end_time.strftime("%H: %M %P")  %></p>
<p>Tutor:
    <%= @booking.teacher_id%></p>
<p>Student:
    <%= @booking.student_id%></p>

<div class="controls">
    <%= link_to("Edit this booking", edit_booking_path(@booking)) %>

    <!-- needs to be a button instead of a link to -->

    <%= button_to("Delete", booking_path(@booking), method: :delete, data: {confirm: "Are you sure?"}) %>
     </div> <%= @booking.to_json %>>